"use strict";

const mongoose = require("mongoose");

/**
 * Referral codes are generated BY THE BACKEND (one per user per competition).
 * Reward credit happens ONLY when a referred user completes a real registration
 * (see competitions register route) — never merely because a link was clicked.
 */
const ReferralSchema = new mongoose.Schema(
  {
    competition: { type: mongoose.Schema.Types.ObjectId, ref: "Competition", required: true, index: true },
    ownerUserId: { type: String, required: true, index: true, maxlength: 128 },
    code: { type: String, required: true, unique: true, index: true, maxlength: 64 },
    signupCount: { type: Number, default: 0, min: 0 },
    creditEarned: { type: Number, default: 0, min: 0 },
  },
  { timestamps: true }
);

ReferralSchema.index({ competition: 1, ownerUserId: 1 }, { unique: true });

module.exports = mongoose.model("Referral", ReferralSchema);
